### ISSUE TITLE
Importing page components from different directories

### ISSUE THREAD

**Issue by jesseschutt** [inertiajs/inertia-vue#1]
Thanks for publishing this Jonathan! It looks great!

I'm curious if anyone can point me in a direction for importing page components from multiple directories? The base setup imports all page components from `resources/js/Pages/*` but many of my projects use a modular structure where the page components live in a variety of directories. 

```
Auth
- Resources
- - JS
- - - Pages
User
- Resources
- - JS
- - - Pages
Company
- Resources
- - JS
- - - Pages
... etc
```

How might I modify this snippet to accommodate multiple directories?

```
resolveComponent: (component) => {
  return import(`@/Pages/${component}`).then(module => module.default)
}
```

Thanks in advance!

**Comment by reinink** [comment]
Interesting. This technique relies on Webpack's [dynamic imports](https://webpack.js.org/guides/code-splitting/#dynamic-imports), and I'm honestly not sure how flexible that feature is. Have you tried something like this?

```js
/*
Component names:
    - Auth/Index
    - User/Index
    - User/Create
    - User/Edit
    - Company/Index
    - Company/Create
    - Company/Edit
*/

resolveComponent: (component) => {
  let parts = component.split('/')
  let section = parts[0]
  let page = parts[1]

  return import(`@/${section}/Resources/JS/Pages/${page}`).then(module => module.default)
}
```

**Comment by Rux77** [comment]
I came a cross a use case like this before. So what you can do is:

in **package json** add ( user, company.. etc) screipts:

```json
      "scripts": {
        "user-dev": "npm run user-development",
        "user-development": "cross-env process.env.section=user NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
        "user-watch": "npm run user-development -- --watch",
        "user-watch-poll": "npm run user-dev -- --watch-poll",
        "user-hot": "cross-env process.env.section=user node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
        "user-prod": "npm run user-production",
        "user-production": "cross-env process.env.section=user NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
        "company-dev": "npm run company-development",
        "company-development": "cross-env process.env.section=company NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
        "company-watch": "npm run company-development -- --watch",
        "company-watch-poll": "npm run company-dev -- --watch-poll",
        "company-hot": "cross-env process.env.section=company node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
        "company-prod": "npm run company-production",
        "company-production": "cross-env process.env.section=company NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
    },
```

Then **webpack.mix.js** will be:
```js
if (process.env.section) {
  require(`${__dirname}/webpack.mix.${process.env.section}.js`)
}
```

Then add "webpack.mix.**user**.js" and "webpack.mix.**company**.js" files in your root folder:
Each file has its own mix instance

So for example for "webpack.mix.**company**.js" file: 

```js
const mix = require("laravel-mix");
require("laravel-mix-auto-extract");

mix.js("resources/js/company/app.js", "public/js/company")
    .sass("resources/sass/company/app.scss", "public/css/company")
    .autoExtract({
        vendorPath: "js/company/vendor",
        manifestPath: "js/company/manifest",
        excludeRegExp: /^.*\.(css|scss|sass|less|styl)$/,
        generateManifest: true,
    });


mix.webpackConfig({
    output: {
        chunkFilename: mix.inProduction() ? "js/company/chunks/[name].[chunkhash].js" : "js/company/chunks/[name].js"
    }
});
```

**Comment by reinink** [comment]
Closing this, but feel free to continue the discussion if needed. I don't think there are any changes here that we need to make to the Vue adapter.

**Comment by yashiroiori** [comment]
This solution work with modules in Laravel and custom package

**Comment by xavi7th** [comment]
Hello all. Thanks for a wonderful package.

@yashiroiori your suggestion is great and that fixed this issue for me with a few tweaks. But it got me thinking that I would rather fix this on the server side rather than multiple ifs in my app.js.

Can I propose a recommendation that could fix this. server side? How about we have an API similar to setRootView available in the Facade? Maybe call it setComponentRoot. This way in our AppServiceProvider for a particular "Controller", we can set the root folder Inertia scans for template.

public function setRootView($name)
    {
        $this->rootView = $name;
    }

public function setComponentRoot($name)
    {
        $this->componentRoot = $name;
    }

Then we would have the render method thus

 public function render($component, $props = [])
    {
        if ($props instanceof Arrayable) {
            $props = $props->toArray();
        }
        
        return new Response(
            $this->componentRoot . $component,
            array_merge($this->sharedProps, $props),
            $this->rootView,
            $this->getVersion()
        );
    }

The benefit of this is that it makes it very flexible for developers to bundle their "view" files where they like and still have a wonderful experience with Inertia.

Thanks again for an awesome package.
