### ISSUE TITLE
integration con vuetify?

### ISSUE THREAD

**Issue by imard28** [inertiajs/inertia-vue#100]

**Comment by Juhlinus** [comment]
Hello @imard28 !

Have you tried installing Vuetify and having issues with it?

I haven't used Vuetify myself, but I don't see why it would be an issue using it together with Inertia.

**Comment by imard28** [comment]
Hi. if it seems to be due to the loading of dynamic components. 
the error is that v-app does not recognize it as a component

**Comment by xalunda** [comment]
Hi @imard28 
I'm currently working on an integration of Inertia with Vuetify@2.1.

I'll make a public repo and share it here by the end of the week :)

**Comment by reinink** [comment]
So, I don't use Vuetify, but I agree with @Juhlinus, there really isn't any reason you can't with Inertia.js. Inertia is a very thin layer between your back-end and front-end. Really, an Inertia Vue.js app is pretty much a standard Vue.js app, just without the client-side routing.

Awesome @xalunda, thanks for your willingness to do that 👍

**Comment by xalunda** [comment]
Hi there!

Project up an running 👍 

https://github.com/xalunda/inertiajs-laravel-vuetify

Enjoy! Hope this helps
