### ISSUE TITLE
419 Error immediately after login

### ISSUE THREAD

**Issue by Ravelin** [inertiajs/inertia-vue#101]
Hi,

I am currently getting a 419 error whenever I try and post anything, this happens immediately after signing in. 

I have tried the fixes in the 419 closed issues and I am still getting the error.

Sample package.json
    "@inertiajs/inertia": "dev-masterv#0.1.7",
    "@inertiajs/inertia-vue": "dev-masterv#0.1.2",

Sample Composer.json
    "tightenco/ziggy": "^0.8.1"

//ziggy route handler
Vue.prototype.$route = (...args) => route(...args).url()

example route

      this.$inertia
        .post(this.$route("controller.method"), value)
        .then(() => {
          if (this.$page.flash.success != null) {
            alertify.success(this.$page.flash.success);
          }
        });

or

        <inertia-link
          :href="$route('logout')"
          method="post"
        >Logout</inertia-link>

Both of the above links result in a 419 error.  I have tested the token and it matches to what is sent, I am not idling this is an immediate click once I have logged in and still results in a 419 error.

Any help would be greatly appreciated.

**Comment by RSpeekenbrink** [comment]
I guess you're using inertia together with Laravel? Did you add your CSRF token to your blade and to axios?

In app.blade.php:
```php
<!-- CSRF Token -->
<meta name="csrf-token" content="{{ csrf_token() }}">
```

In app.js (or where you initialize axios):
```js
/**
 * We'll load the axios HTTP library which allows us to easily issue requests
 * to our Laravel back-end. This library automatically handles sending the
 * CSRF token as a header based on the value of the "XSRF" token cookie.
 */

window.axios = require('axios');

window.axios.defaults.headers.common['X-Requested-With'] = 'XMLHttpRequest';

/**
 * Next we will register the CSRF Token as a common header with Axios so that
 * all outgoing HTTP requests automatically have it attached. This is just
 * a simple convenience so we don't have to attach every token manually.
 */

let token = document.head.querySelector('meta[name="csrf-token"]');

if (token) {
    window.axios.defaults.headers.common['X-CSRF-TOKEN'] = token.content;
} else {
    console.error('CSRF token not found: https://laravel.com/docs/csrf#csrf-x-csrf-token');
}
```

**Comment by Ravelin** [comment]
Yeah, all the is configured correctly as if I refresh the page it works as intended, it's just a mismatch from the version that is set on login to the version that is posted when I post a request to the backend.

**Comment by gregupton** [comment]
You don't need to add the CSRF meta tag to your blade or in your app.js, intertia/axios takes care of this for you. 

See @reinink's post on CSRF [#32](https://github.com/inertiajs/pingcrm/issues/32#issuecomment-517950878), I have run into this issue when the permissions are not setup correctly on the /storage directory.

**Comment by reinink** [comment]
Also, see the docs [here](https://inertiajs.com/security#csrf-protection).

If you're using Laravel, you don't need to do any csrf configuration. It works out of the box. Note, the CSRF configuration was recently removed from Laravel. See [here](https://github.com/laravel/laravel/pull/5083).

**Comment by Ravelin** [comment]
It doesn't work if I have the CSRF token in or out it still returns a 419 error,  still fails at the same point of I login, tokens are matched, I try posting something and it returns a 419 error.

I login, refresh page, do same action, works as it should.

**Comment by jartaud** [comment]
I'm having the same problem as @Ravelin . Sometimes after login i got 419 if i try to post something. It works great after a hard refresh.

**Comment by bakerkretzmar** [comment]
For anyone else still struggling with this, if you're using Ziggy, make sure you're calling `route(...).url()` and not just `route(...)`.

https://github.com/inertiajs/inertia-vue/issues/39#issuecomment-494425358
