### ISSUE TITLE
Cannot read property 'call' of undefined in Production

### ISSUE THREAD

**Issue by Juhlinus** [inertiajs/inertia-vue#102]
Some people are having issues with the compilation in the production environment.

![Screen_Shot_2019-10-30_at_3 37 23_PM](https://user-images.githubusercontent.com/12988164/67865752-1b7dbe80-fb28-11e9-9bbf-957189619163.png)

@kabbouchi was kind enough to do some debuggin of this and found that if you use styles in your Vue components as well as specifying `.sourceMaps()` in your mix file, then this results in the above error message on compilation.

We have had a developer that did not make use of `.sourceMaps()` but still encountered the error. It is unclear if this developer is using style tags in their Vue components.

This is an issue that only occurs when running the production script.

I'm going to see if I can investigate this myself when time allows.

**If you are having this issue, then please react with the 👀 emoji.**

**Comment by KABBOUCHI** [comment]
Minimal Reproduction:

1- Add style to `resources/js/Pages/Auth/Login.vue`
```html
<style>
.red {
  color: red
}
</style>
```
2- run `npm run prod`

3- Open login page

![image](https://user-images.githubusercontent.com/9212274/67866931-54bb2c00-fb32-11e9-88f7-967ad66f05db.png)

**Comment by njoguamos** [comment]
I had a similar issue sometime back and I think [this explanation could help](https://github.com/inertiajs/inertia-vue/issues/4)

For my case, the error was as a result of using (dynamic imports and code splitting) and having styles on my components. Interesting enough the error occurred on production only while there was no problem during dev (yarn watch).

I ended up resolving the issue by disabling dynamic imports and code splitting. 😔

```php
// Instead of this
resolveComponent: name => import(`@/Pages/${name}`).then(module => module.default),

// I am doing this
resolveComponent: name => pages(`./${name}.vue`).default,
```

@KABBOUCHI you could try disabling dynamic imports and let me know it that works for you

**Comment by devonmather** [comment]
My issue doesn't directly relate to this. I was just curious as to solutions in case something showed up regarding an issue I'm having with production builds. I have experienced this issue and simply resigned myself to removing all style tags from Vue components for the time being.

**Comment by Juhlinus** [comment]
The aforementioned developers have confirmed that removing styles in their components fixes this issue.

Closing.

**Comment by atymic** [comment]
I came across this as well :(

Did anyone manage to fix it without just removing the styles?

**Comment by KABBOUCHI** [comment]
@atymic try to include source maps in production `.sourceMaps(true)`

**Comment by reinink** [comment]
@Juhlinus Is this not a Laravel Mix issue?

**Comment by Juhlinus** [comment]
Yeah, we just had a couple of guys in the discord who all suddenly reported the same issue. So I basically just wanted to make sure that this wasn't a different and widespread issue. 😄
