### ISSUE TITLE
Where to add asset versioning?

### ISSUE THREAD

**Issue by paulotra** [inertiajs/inertia-vue#103]
I need help where to add this code?

```
Inertia::version(function () {
    return md5_file(public_path('mix-manifest.json'));
});
```

**Comment by reinink** [comment]
I'd recommend putting this in your app service provider. 👍

**Comment by paulotra** [comment]
I already tried that, but didn't fix my issue. My issue is same as is this one https://github.com/inertiajs/inertia-vue/issues/94

**Comment by Juhlinus** [comment]
> @reinink I already tried that, but didn't fix my issue. My issue is same as is this one #94

If you're using style tags in your Vue components then remove them and it should work for you.

**Comment by paulotra** [comment]
> > @reinink I already tried that, but didn't fix my issue. My issue is same as is this one #94
> 
> If you're using style tags in your Vue components then remove them and it should work for you.

What if that component is a 3rd party package?

**Comment by Juhlinus** [comment]
> > > @reinink I already tried that, but didn't fix my issue. My issue is same as is this one #94
> > 
> > 
> > If you're using style tags in your Vue components then remove them and it should work for you.
> 
> What if that component is a 3rd party package?

Try adding `.sourceMaps(true)` to your `webpack.mix.js` file.

**Comment by paulotra** [comment]
> > > > @reinink I already tried that, but didn't fix my issue. My issue is same as is this one #94
> > > 
> > > 
> > > If you're using style tags in your Vue components then remove them and it should work for you.
> > 
> > 
> > What if that component is a 3rd party package?
> 
> Try adding `.sourceMaps(true)` to your `webpack.mix.js` file.

Thanks man, just fixed by copying that component and removing style that's imported to it.
