### ISSUE TITLE
How to access `$page` property in script section

### ISSUE THREAD

**Issue by bedus-creation** [inertiajs/inertia-vue#109]

**Comment by Juhlinus** [comment]
Hi there @bedus-creation !

If you want to access the $page property in the script section then you just write `this.$page`. Similarly, if you want to use it in your Vue component, then use access the properties like this: `<p>{{ $page.foo }}</p>`

If you ever have any questions about how things are done then I'd recommend checking out [PingCRM](https://github.com/inertiajs/pingcrm).

**Comment by reinink** [comment]
I'm assuming this answered the question. Thanks @Juhlinus! 👍
