### ISSUE TITLE
Using Laravel-Mix BrowserSync results in 431 (Request Header Fields Too Large).

### ISSUE THREAD

**Issue by marbuser** [inertiajs/inertia-vue#113]
Initially it was working quite well but as soon as I started using more than 1 route it started to error out and state; `431 (Request Header Fields Too Large)` inside my browser console.

Not really sure where the problem lies but after disabling BrowserSync and restarting with just regular `watch` it started working fine again.

**Comment by ravenberg** [comment]
Hi, I've been using a setup with browsersync and multiple routes succesfully while using react. Im curious as to how we can reproduce the error.

**Comment by reinink** [comment]
I don't use BrowserSync myself, but check out this issue: https://github.com/inertiajs/inertia-laravel/issues/16

I don't think this is really an Inertia.js issue, but rather a BrowserSync/Laravel Mix/Webpack issue. For that reason I am going to close this.

If you do figure this out, please report back. 👍
