### ISSUE TITLE
NProgress bar shows once and then never again.

### ISSUE THREAD

**Issue by marbuser** [inertiajs/inertia-vue#114]
I've included the NProgress css successfully and when navigating to a route, it shows, but it only does it once. No matter how many different routes I go to after that, it will not show up again.

It only shows up again when I bust the cache and it will again do it once, and then never again.

I'm incredibly confused as to why this is happening. Hopefully someone can explain.

**Comment by Juhlinus** [comment]
Hi @marbuser ! 

The NProgress bar is only showed if the request takes more than 250ms.

**Comment by marbuser** [comment]
@Juhlinus Ah, I think this should be added to the docs. I was absolutely pulling my hair out at why this wasn't working! 😅

Is it possible for me to force it to always show or add some sort of request simulation so that I can do correct styling on local dev for it?

**Comment by reinink** [comment]
I've added a note [about this](https://inertiajs.com/client-side-setup#loading-indicator) in the documentation.

There is no way to customize the time (250ms) right now, but we intend to give more control over the loading indicator in the future (see [here](https://github.com/inertiajs/inertia/issues/9)).

You can test this locally by adding a delay server-side (eg. `sleep(2)`), or even just using the Chrome throttling tools.

Hope that helps! 👍
