### ISSUE TITLE
Peristant Data access

### ISSUE THREAD

**Issue by roni-estein** [inertiajs/inertia-vue#115]
Hey, I'm sure this is easy and I'm just missing it. However, right now, if I want to access shared data in the template, I can access it through the `$pages.(something)`depending on my shared information in AppServiceProvider.

However I can't figure out how to access this data in the script section.

for example, pulled from ping crm:

```
export default {
	metaInfo: {title: 'Update Profile | ' + $pages.auth.user.name}, <- nope
	layout: Layout,
```

OR

```
data() {
  return {
    sending: false,
      form: {
        id: $pages.auth.user.id, <- also not available.
```

I must be accessing the shared data incorrectly, right now, I'm just passing it in as a prop, which just seems like a waste.

Thanks in advance.
Cheers.

**Comment by Juhlinus** [comment]
Hello @roni-estein !

The following should work:
`this.$pages.auth.id`

**Comment by reinink** [comment]
Yup, @Juhlinus is correct. Closing this.
