### ISSUE TITLE
Error in render: "SyntaxError: Unexpected token u in JSON at position 0"

### ISSUE THREAD

**Issue by wrtisans** [inertiajs/inertia-vue#118]
i've this error on a new install in laravel with vue

![CleanShot 2020-01-27 at 21 44 49](https://user-images.githubusercontent.com/44764875/73234095-5bb40380-414e-11ea-8c4b-b23b6563097a.png)

this is my app.js 

![image](https://user-images.githubusercontent.com/44764875/73234137-87cf8480-414e-11ea-8909-685eceb8640c.png)

**Comment by DjustinK** [comment]
@wrtisans How did you fix this?

**Comment by wrtisans** [comment]
i've not fixed this, i've uses another framework

**Comment by josespinal** [comment]
Hi, if anyone else comes to this issue. The "u" is from _undefined_ make sure you include:
`<div id="app"></div>`  In your layout blade file. 

**_Bonus:_**
If you did include this and not sure what is going on, debug by looking at the console logging the app constant from your app.js file" `console.log(app);` to see if HTML is generate wrong somehow and JS can't find the DOM "#app" element.

**Comment by v1nk0** [comment]
If you use the Laravel adapter be sure that your view-file is called "app.blade.php" (see https://inertiajs.com/server-side-setup > _Root template_)
