### ISSUE TITLE
How to implement Loading Bar

### ISSUE THREAD

**Issue by gajosadrian** [inertiajs/inertia-vue#121]
Hello,

how to implement loading bar on the top of page for every routing? It's in Ping CRM demo and I can't really find out which Component does the animation.

**Comment by Juhlinus** [comment]
Hey @gajosadrian it's included by default, but only shows if the request takes longer than 250ms.

See here: https://github.com/inertiajs/inertia/blob/fc4775ce33f6e8875b76e11973aedfba209ff476/src/progress.js#L12-L16

**Comment by gajosadrian** [comment]
```
        sleep(5);
        return Inertia::render('Admin/Index');
```
I did such and still the bar isn't showing up.

**Comment by georgehanson** [comment]
You need to make sure you include the [nprogress CSS](https://github.com/rstacruz/nprogress/blob/master/nprogress.css) in your build. From the [docs](https://inertiajs.com/client-side-setup#loading-indicator)...

>Be sure to include the nprogress.css in your project, otherwise you won't see it.

**Comment by gajosadrian** [comment]
> You need to make sure you include the [nprogress CSS](https://github.com/rstacruz/nprogress/blob/master/nprogress.css) in your build. From the [docs](https://inertiajs.com/client-side-setup#loading-indicator)...
> 
> > Be sure to include the nprogress.css in your project, otherwise you won't see it.
