### ISSUE TITLE
Noob Question

### ISSUE THREAD

**Issue by mmoore99** [inertiajs/inertia-vue#122]
Is it possible to pass props to a persistent layout in Vue? If so, how?

Thanks.

**Comment by Juhlinus** [comment]
Hello @mmoore99 !

What are you going to be using these props for? Depending on your use case there might be one or several ways to go about solving this.

Going off of just your question I'm guessing you might be interested in [reading about shared data](https://inertiajs.com/shared-data).

**Comment by mmoore99** [comment]
Shared data will not solve this. I want to have props in the layout that are injected by the page component that is using the layout. The values of those props would be specific to the particualr component.

**Comment by Juhlinus** [comment]
Ah, what you're trying to solve is passing a prop from a child component to a parent component.

What you want is an **Event Bus**.

https://alligator.io/vuejs/global-event-bus/
https://css-tricks.com/using-event-bus-to-share-props-between-vue-components/

**Comment by victorlap** [comment]
If you'd like to set the page title / meta or something, check out the sample in (a previous version of) the pingcrm app.

In [a page](https://github.com/inertiajs/pingcrm/blob/8f2a6f57e09482ad3ae29a5fb928806a2980da75/resources/js/Pages/Contacts/Index.vue#L2) the title is set, which is used in the parent [layout](https://github.com/inertiajs/pingcrm/blob/8f2a6f57e09482ad3ae29a5fb928806a2980da75/resources/js/Shared/Layout.vue#L66).

**Comment by mmoore99** [comment]
> Ah, what you're trying to solve is passing a prop from a child component to a parent component.
> 
> What you want is an **Event Bus**.
> 
> https://alligator.io/vuejs/global-event-bus/
> https://css-tricks.com/using-event-bus-to-share-props-between-vue-components/

Duh, of course, thank you. In trying to get my head around all of the inertia stuff I got confused regarding basic Vue stuff. For some reason I was thinking the layout was the child component. Thanks for setting me straight.

**Comment by Juhlinus** [comment]
@mmoore99 Great! If you feel your issue has been solved, then don't forget to close this issue. 😄
