### ISSUE TITLE
route not updated in child components

### ISSUE THREAD

**Issue by quaidesbalises** [inertiajs/inertia-vue#125]
Hi,

I don't know if this issue is related to inertia but this is what happened : 

I have a **Dashboard.vue** which extends a **Board.vue** layout.

If I put this code in the layout file, ```Route : {{route().current()}}```, the route variable is updated correctly when I change page.

Layout file : 

```vue

<template>
	<div v-cloak>
		
		<sidebar></sidebar>

	    <div class="main-content">

	    	Route : {{route().current()}}

	    	<flash-message></flash-message>
	    	<topbar></topbar>
			
			<div class="container-fluid mb-5">
	        	<transition name="slide-fade" appear>
	        		<slot />
	        	</transition>
	        </div>

	    </div>

	    <div id="modals">
	    </div>

	</div>
</template>

<script>

	import Sidebar from '@partials/navbar/Sidebar'
	import Topbar from '@partials/navbar/Topbar'

	export default {
		components: {
			Sidebar, 
			Topbar
		}
	}

</script>

``` 

But, if I put this piece of code (```Route : {{route().current()}}```) inside a component which is on this layout, for example **topbar**, the route variable is not updated and stay at its initial value.

What is the issue here ?

**Comment by quaidesbalises** [comment]
Ok I found it but this is very strange.  It works only if I call the ```$page``` variable in the component otherwise the ```route().current()``` doesn't update.

You can experience it in the pingcrm project : 

**1.** Create a **shared/Test.vue** file  : 

```vue
<template>
	<div :page="$page">
		Current route : {{route().current()}}
	</div>
</template>

<script>
	export default {

	}
</script>
```


**2.** Import it inside for example the **shared/MainMenue.vue** : 

```vue
import Icon from '@/Shared/Icon'
import Test from '@/Shared/Test'

export default {
  components: {
    Icon,
    Test
  } ...
```


At this point if you look at your browser and click links in the main menu, 
the current route is not update.
To make it works, you need to use the **$page** variable inside your project.

For example : 

```vue

<template>
	<div :page="$page">
		Current route : {{route().current()}}
	</div>
</template>

```

------------ 

@reinink , Do you think this is a normal behaviour and if it is can you explain me why ? 
I'm very curious about it.  Thanks  ;)

**Comment by reinink** [comment]
Hey @quaidesbalises! This is Vue behaviour and not really and Inertia.js issue. Vue will not reactively update based on `window` state. It will only do this for data it tracks.

You can work around this by passing this value as a prop to a sub component.

For example, in Ping CRM, the [layout](https://github.com/inertiajs/pingcrm/blob/master/resources/js/Shared/Layout.vue#L14) component passes a `url` prop to the [main menu](https://github.com/inertiajs/pingcrm/blob/master/resources/js/Shared/MainMenu.vue#L38) component.

Hope that helps!
