### ISSUE TITLE
Help me with file upload using PUT or PATCH. (Posting file works fine)

### ISSUE THREAD

**Issue by VivaJosh** [inertiajs/inertia-vue#136]
Hi there, I setup Intertia Vue with Laravel it is amazing

Reading the docs I set up a form upload with this.$inertia.post('url', data) with FormData everything works well, I can receive the file in backend. 

But if i try to post to the update method (Laravel backend) with this.$inertia.put('url', data), i can only get the form fields excluding the image file bag is empty, 
I tried this.$inertia.patch('url', data) file bag is still empty

but if i change to this.$inertia.post('url', data) file bag will contain the file. 

Please any heads up with PATCH, PUT with file upload?

**Comment by Juhlinus** [comment]
This is an issue with core PHP, actually.

https://bugs.php.net/bug.php?id=55815

Add a new field to your `form input` called `_method` and set it to `put` and you should be good to go. You still need to use `$inertia.post`, but it will be handled as a `put` request by Laravel.

https://github.com/inertiajs/pingcrm/blob/master/resources/js/Pages/Users/Edit.vue#L86

**Comment by VivaJosh** [comment]
Thank you so so much. 
solved the problem
