### ISSUE TITLE
npm run production does not disable devtools

### ISSUE THREAD

**Issue by SamuelNitsche** [inertiajs/inertia-vue#15]
First of all, thank you for this amazing product. I really love playing with it.

While tinkering around I noticed that running `npm run production` in the pingcrm demo app does not disable vue devtools. After a bit of testing and searching for this problem I found [this](https://stackoverflow.com/questions/41431167/webpack-compiling-vue-with-node-env-production-still-results-in-dev-warning/41627264#41627264) post where the solution is to change the vue alias to `vue/dist/vue.common.js` instead of `vue/dist/vue.runtime.js`.

I immediately tested this and like expected, vue devtools are disabled. Further, I did not notice any difference or error. Is there any specific reason for using `vue.runtime.js` instead of `vue.common.js`?

Thank you very much for your help!

**Comment by cmizzi** [comment]
You should use `vue/dist/vue.runtime.common.js`. It handles development/production code (https://vuejs.org/v2/guide/installation.html#Explanation-of-Different-Builds).

**Comment by SamuelNitsche** [comment]
I see. Is this something we should create a pr for?

**Comment by reinink** [comment]
Thanks folks! So, I looked into this, and you're right `vue/dist/vue.runtime.js` isn't what we should be using. I've done a quick test:

- **vue/dist/vue.runtime.js:**
    - 116,413 bytes
    - Has devtools
- **vue/dist/vue.runtime.common.js:**
    - 103,109 bytes
    - No devtools
- **vue/dist/vue.runtime.esm.js:**
    - 103,389 bytes
    - No devtools

So `vue.runtime.common.js` and `vue.runtime.esm.js` are almost the same size, with both no devtools enabled.

Going off [this section](https://vuejs.org/v2/guide/installation.html#Terms) of the docs, it seems to suggest that `vue.runtime.esm.js` is actually the right choice, I'm going to roll with that.

Thanks again for pointing this out @SamuelNitsche!
