### ISSUE TITLE
Add abillity to transform prop data

### ISSUE THREAD

**Issue by thoresuenert** [inertiajs/inertia-vue#19]
### Idea
Be able to transform any prop data to custom objects, like errors to an errorbag.

Instead of accessing errors by index, example from pingcrm:

```js
// TextInput.vue
<template>
    <div v-if="errors.length" class="form-error">{{ errors[0] }}</div>
</template>
```

We want to work with an ErrorBag Object which has functions like `has`, `any` and `first`:

```js
<div v-if="errors.has('email')"> {{ errors.first('email')}} </div>
```

### Solution

Add a `transform` hook/method:

```js 
import Errors from '@/Shared/Errors'
new Vue({
    components: {
        Flash
    },
    render: h => 
        h(Inertia, {
            props: {
                initialPage: JSON.parse(app.dataset.page),
                resolveComponent: (component) => {
                    return import(`@/Pages/${component}`).then(module => module.default)
                },
                transform: ({ errors, ...props}) => {
                    return {
                        errors: new Errors(errors),
                        ...props
                    }
                },
            },
        }),
}).$mount(app)
```

Maybe others can benefit from this layer of transformation.
I can think of transform data to model object etc.

**Comment by MichaelDeBoey** [comment]
I don't see the point of it, since you're in control of both frontend and backend.  
So you can just send your props the way you want from your backend, no?

**Comment by thoresuenert** [comment]
I This particular example with errors, I use the whole array of errors for a particular field and only the first one. 

Yeah I can share what ever I want with inertia, but giving the errors as object of arrays is default behavior of laravel.

**Comment by thoresuenert** [comment]
Yeah you are right. I could only pass one error for each to inertia. 

But in different forms I need sometimes multiple errors and in an other form only the first one. Like the laravel errorbag provide that. 

There is nothing wrong about using the arrays directly, but from my point of view the object way is my favorite way to go.

I opened the issue if anyone else have ideas where this hook can be useful. 

@reinink already said that a merge of this feature is unlikely.

**Comment by thoresuenert** [comment]
When I do the transformation in the page component with:

‘’’js

data() { 
  return { 
    errros: new Errors(this.errorsprop) 
  }
}

‘’’

I had reactivity issues. After sending the form the errors stated empty.

**Comment by cmizzi** [comment]
You should use them like that (in order to be reactive). But, if a request is made using AJAX, you have to handle the `errorsbag` variable from the Promise returned by the request. Inertia will not do that for you.

```js
export default {
  props: ['errors'],

  data () {
    return {
      errorsbag: null
    }
  },

  watch: {
    errors: {
      immediate: true,
      handler (errors) {
        this.errorsbag = new Errors(errors)
      }
    }
  },

  methods: {
    /**
     * if the request is done using this method
     *
     * @param {Object} fields
     */
    onSubmit (fields) {
      this.$axios.post('/my-route', { body: fields }) 
        .then((response) => {
          // do something
        })
        .catch((error) => {
          this.errorsbag = new Errors(error.errors)
        })
    }
  }
}
```

**Comment by rakk7** [comment]
> You should use them like that (in order to be reactive). But, if a request is made using AJAX, you have to handle the errorsbag variable from the Promise returned by the request. Inertia will not do that for you.

In case of AJAX, maybe I think an Axios response interceptor to handle the errors and errorsbag is the way to go.

**Comment by thoresuenert** [comment]
@cmizzi thanks for your solution. a watcher would work in that situation.

pretty much to code to achive a littel detail so...

I am using inertia.post to send forms, so i dont have to handle ajax respones by myself. inertia will follow redirect and replace all props for me.

**Comment by thoresuenert** [comment]
My solution for this right now (thanks @cmizzi):

```js
// Service/Errors/Mixin
import Errors from './Errors'

export default {
    props: {
        errorsbag: Object
    },
    data() {
        return {
            errors: null,
        }
    },
    watch: {
        errorsbag: {
            immediate: true,
            handler(errorsbag) {
                this.errors = new Errors(errorsbag)
            }
        }
    },
}
```
use the mixin where handling errors is needed like:
```js
// Page Component
import HandleErrors from "@/Service/Errors/Mixin";

export default {
    mixins: [HandleErrors],
    ...
}
```

and on the laravel side:

```php
 Inertia::share('errorsbag', function () {
            return Session::get('errors') ? Session::get('errors')->getBag('default')->getMessages() : (object) [];
        });
```

**Comment by reinink** [comment]
Another option is to use a computed property here. I feel like that's probably the more idiomatic Vue way of doing this. As per the Vue docs:

> Vue does provide a more generic way to observe and react to data changes on a Vue instance: watch properties. When you have some data that needs to change based on some other data, it is tempting to overuse watch - especially if you are coming from an AngularJS background. However, it is often a better idea to use a computed property rather than an imperative watch callback.

So, instead of using a watcher, do this:

```js
{
  computed: {
    errors() {
      return new Errors(this.errorsbag)
    }
  }
}
```
