### ISSUE TITLE
Method "route" has type "undefined" in the component definition.

### ISSUE THREAD

**Issue by jeremytubbs** [inertiajs/inertia-vue#3]
I followed your intro video... Could you help me with these warnings?

![image](https://user-images.githubusercontent.com/548888/56061566-c6b75980-5d37-11e9-9649-d4a04cea227f.png)

**Comment by jeremytubbs** [comment]
🔥Adding https://github.com/tightenco/ziggy and `@routes` to `app.blade.php` removed the warnings.

**Comment by reinink** [comment]
Yepper, that's the trick! That's for updating this issue with the solution.

**Comment by lucaros97** [comment]
Ziggy works perfectly 👌
