### ISSUE TITLE
Getting 419 response code on submit

### ISSUE THREAD

**Issue by pepeloper** [inertiajs/inertia-vue#39]
I'm making a post request to a url via post method and I keep getting the 419 (page expired) response code.

So this is the way the submit handler calls the url.
```
this.$inertia.post('/folders', data).
```
Then if I inspect the network tab on chrome, the request doesn't have the `X-XSRF-TOKEN` header.

I don't know if I'm missing something, but i gave a look at the pingcrm repository and didn't see any extra configuration needed for this, so I'm a little bit lost here

**Comment by reinink** [comment]
Hey! What server-side framework are you using?

Axios will automatically add the `X-XSRF-TOKEN` header if it exists in a cookie called `XSRF-TOKEN`. Some server-side frameworks do this automatically. For example, Laravel does this using the `VerifyCsrfToken` middleware:

https://github.com/laravel/framework/blob/12cf3f482db8ef65fe9f2a97c3e9ebde1765e21d/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php#L176-L188

**Comment by reinink** [comment]
Closing this because I don't think this is an Inertia issue, but feel free to still respond and I'll happily try and help figure this out with you. 💪

**Comment by pepeloper** [comment]
I'm using Laravel as a backend, and as you pointed out I have checked the XSRF-TOKEN cookie and it's present.

I'm going on to a look around and update this issue if I figure out something new, thanks for your help!!

**Comment by pepeloper** [comment]
Ok i've solved it and sincerely i don't know what was wrong. I'm working on another machine and I have rebuilt that little functionality and now it's working, I think I was missing some piece of data in my call that made it fail in that way.

**Comment by reinink** [comment]
Were you, by any chance, using the Ziggy library?

I have noticed, that for some strange reason, if you use `route('posts.index')` the XSRF-TOKEN isn't applied in Axios, but if you use `route('posts.index').url()` it will.

More info here: https://github.com/tightenco/ziggy/pull/64#issuecomment-332858868

**Comment by pepeloper** [comment]
OMG!! I think that's it, I'm using it right now and that's the difference. Thanks for spot it!

**Comment by reinink** [comment]
Glad I could help. This is why I do this in the PingCRM demo app:

https://github.com/inertiajs/pingcrm/blob/6419ed3a89c89374141d01fc923916d9052806b3/resources/js/app.js#L6

**Comment by RobertBoes** [comment]
I _think_ it has something to do with Axios not converting the ziggy object to a string. Since a string in JS always has the `.toString()` method, adding `url.toString()` when the url is passed to Axios should fix this, right? Right about here: https://github.com/inertiajs/inertia/blob/d0fc74fb85525d2fa1c1ed05439ad23b5943c1b1/src/inertia.js#L50

In my app I now just do `this.$inertia.post(this.route('login').url(), { ... })` with the default ziggy mixin. See [Router.toString() @ tightenco/ziggy](https://github.com/tightenco/ziggy/blob/253b919cddc196a5a9a94c5d1e406d1b57f700f1/src/js/route.js#L167)

I could make a PR to `inertiajs/inertia` if you'd like. Perhaps with an extra check so it throws an error if the url is not an instance of String.

**Comment by reinink** [comment]
@RobertBoes I like that idea. I've made this change to Inertia (https://github.com/inertiajs/inertia/commit/1a0429a4b84d142b953ff6cec8d15fbb1a698293). Even though I don't see this as Inertia's problem, I think in reality this will just help folks get up and running with the library.

**Comment by bakerkretzmar** [comment]
> I have noticed, that for some strange reason, if you use `route('posts.index')` the XSRF-TOKEN isn't applied in Axios, but if you use `route('posts.index').url()` it will.

Holy hell thank you so much... I've been pulling my hair out for months trying to figure out why me making the same Axios call Intertia makes, manually, was always giving me a 419, and it was Ziggy all along.
