### ISSUE TITLE
about change the laravel default User model

### ISSUE THREAD

**Issue by xoxoj** [inertiajs/inertia-vue#44]
hi, i read the code:

`
return Inertia::render('Users/Index', [
            'filters' => Request::all('search', 'role', 'trashed'),
            'users' => Auth::user()->account->users()
                ->orderByName()
                ->filter(Request::only('search', 'role', 'trashed'))
                ->get()
                ->transform(function ($user) {
                    return [
                        'id' => $user->id,
                        'name' => $user->name,
                        'email' => $user->email,
                        'owner' => $user->owner,
                        'deleted_at' => $user->deleted_at,
                    ];
                }),
        ]);
`

i dont understand this line:

`'users' => Auth::user()->account->users()`

Q1:what the account from?

i saw has one model name called Account, inside has:

`
class Account extends Model
{
    public function users()
    {
        return $this->hasMany(User::class);
    }
    ...
}
`
so, the account from here?

Q2: and I also dont understand the 

`'users' => Auth::user()->account->users()`

users() function from where?

also from here?:

`
public function users()
    {
        return $this->hasMany(User::class);
    }
`
thanks!

**Comment by reinink** [comment]
Each user in PingCRM belongs to an account. Think of the account as the tenant in a multi-tenant app.

```php
Auth::user()->account->users()
```

This says, "give me the users for the account of the currently logged in user". The `users()` method is a relationship on the `Account` model.

https://github.com/inertiajs/pingcrm/blob/master/app/Account.php#L9-L12

Similarly, you can see in the `User` model that they belong to an `Account`:

https://github.com/inertiajs/pingcrm/blob/master/app/User.php#L20-L23

This is pretty standard "Laravel stuff", and isn't really an Inertia thing.

Hope that helps!

**Comment by xoxoj** [comment]
if I guess is right.

then I want change the Laravel default UserModel, and I change the code like:

Account.php code:

`
class Account extends Model
{
    public function workers()
    {
        return $this->hasMany(Worker::class);
    }

    public function organizations()
    {
        return $this->hasMany(Organization::class);
    }

    public function contacts()
    {
        return $this->hasMany(Contact::class);
    }
}
`

and 

'users' => Auth::user()->account->workers()

then system give some error

![313131](https://user-images.githubusercontent.com/1118723/58180533-dd5cb300-7cdc-11e9-8bd9-463424212adb.jpg)

**Comment by reinink** [comment]
Yes, you should be able to make a change like that. You'll need to add a `Worker` model, update the relationships, and create a database table (migration) for it as well.

These are more Laravel related questions, probably better asked in Laravel channel, such as https://larachat.co/ or https://laracasts.com/discuss.

Good luck!

**Comment by xoxoj** [comment]
I change the User.php to Worker.php

and I use migration create workers table.

but get the error...

**Comment by reinink** [comment]
I appreciate that, but unfortunately don't have time to offer that level of support.

Also, note this comment at the top of the readme:

> **Note:** This project is in the very early stages of development and IS NOT yet intended for public consumption. If you submit an issue, I do not guarantee a response. Please do not submit pull requests without first consulting me on Twitter ([@reinink](https://twitter.com/reinink)).

**Comment by xoxoj** [comment]
hahahhaha, thank you!

**Comment by xoxoj** [comment]
hahahhaha, thank you!
