### ISSUE TITLE
Add style to component page then console.log error

### ISSUE THREAD

**Issue by bombiGo** [inertiajs/inertia-vue#45]
![inertiavue_css_error](https://user-images.githubusercontent.com/23717822/58368761-0cb13100-7f24-11e9-80e7-45e583b88c7b.png)
I add style to component page then working laravel to "npm run production" but reload login page not render . I show console.log after error !!! . 

I am sorry,  my english is bad. help me , thanks all.

**Comment by reinink** [comment]
Yes, this is a known issue with Laravel Mix and code splitting with Vue components.

See here: #4
And here: https://github.com/JeffreyWay/laravel-mix/issues/1856
And here: https://github.com/JeffreyWay/laravel-mix/issues/1969

Unfortunately there isn't much you can do, other than disable code splitting, or stop using CSS in your Vue components. Or, of course, configure Webpack yourself.

**Comment by adriandmitroca** [comment]
There is one other solution - downgrading to Mix 3, where dynamic imports are fully working.
