### ISSUE TITLE
Page transitions

### ISSUE THREAD

**Issue by orumad** [inertiajs/inertia-vue#46]
Hi! 

First, thank you @reinink for this awesome framework. Now this is my default Laravel - Vue SPA stack.

My question is: Is there a way to animate page transitions? I can't found anything related in the documentation.

Thanks!

**Comment by papalardo** [comment]
I do like this: 

app.js 
`import Inertia from 'inertia-vue'
import Vue from 'vue'
import App from './App.vue'

Vue.use(Inertia)

const app = document.getElementById('app')

new Vue({
    render: h => h(App, {
        props: {
            initialPage: JSON.parse(app.dataset.page),
            resolveComponent: name => import(`@/Pages/${name}`).then(module => module.default),
            transformProps: function (props) {
                this.$emit('changeProps', props)
                return props;
            }
        },
    }),
}).$mount(app)`

App.vue:
`<template>
    <transition name="fade">
        <Inertia v-bind="$props"></Inertia>
    </transition>
</template>
<script>
import Inertia from 'inertia-vue'

export default {
    props: ['initialPage', 'resolveComponent', 'transformProps'],
    components: {
        Inertia,
    },
}
</script>

<style>
.fade-enter-active, .fade-leave-active {
  transition: opacity .5s;
}
.fade-enter, .fade-leave-to /* .fade-leave-active em versões anteriores a 2.1.8 */ {
  opacity: 0;
}
</style>`

It's works. But I need event when click inertia-link to make **loader** between pages.

**Comment by papalardo** [comment]
I do this:

**app.js** 
```javascript
import Inertia from 'inertia-vue'
import Vue from 'vue'

import App from './App.vue'

Vue.use(Inertia)

const app = document.getElementById('app')

new Vue({
    render: h => h(App, {
        props: {
            initialPage: JSON.parse(app.dataset.page),
            resolveComponent: name => import(`@/Pages/${name}`).then(module => module.default),
            transformProps: function (props) {
                this.$emit('changeProps', props)
                return props;
            }
        },
    }),
}).$mount(app)
```
**App.vue:** 
```vue 
<template>
    <transition name="fade">
        <Inertia v-bind="$props"></Inertia>
    </transition>
</template>
<script>
import Inertia from 'inertia-vue'

export default {
    props: ['initialPage', 'resolveComponent', 'transformProps'],
    components: {
        Inertia,
    },
}
</script>

<style>
.fade-enter-active, .fade-leave-active {
  transition: opacity .5s;
}
.fade-enter, .fade-leave-to /* .fade-leave-active em versões anteriores a 2.1.8 */ {
  opacity: 0;
}
</style>
```

It's works. But I need event when click inertia-link to make loader between pages.

**Comment by orumad** [comment]
Thanks!

**Comment by xyNNN** [comment]
> I do this:
> 
> **app.js**
> 
> ```js
> import Inertia from 'inertia-vue'
> import Vue from 'vue'
> 
> import App from './App.vue'
> 
> Vue.use(Inertia)
> 
> const app = document.getElementById('app')
> 
> new Vue({
>     render: h => h(App, {
>         props: {
>             initialPage: JSON.parse(app.dataset.page),
>             resolveComponent: name => import(`@/Pages/${name}`).then(module => module.default),
>             transformProps: function (props) {
>                 this.$emit('changeProps', props)
>                 return props;
>             }
>         },
>     }),
> }).$mount(app)
> ```
> 
> **App.vue:**
> 
> ```
> <template>
>     <transition name="fade">
>         <Inertia v-bind="$props"></Inertia>
>     </transition>
> </template>
> <script>
> import Inertia from 'inertia-vue'
> 
> export default {
>     props: ['initialPage', 'resolveComponent', 'transformProps'],
>     components: {
>         Inertia,
>     },
> }
> </script>
> 
> <style>
> .fade-enter-active, .fade-leave-active {
>   transition: opacity .5s;
> }
> .fade-enter, .fade-leave-to /* .fade-leave-active em versões anteriores a 2.1.8 */ {
>   opacity: 0;
> }
> </style>
> ```
> 
> It's works. But I need event when click inertia-link to make loader between pages.

Thanks for your solution. Do you solved it when you use a Turbolink like "inertia-link"? How do you send a custom event before processing the click to trigger the transition?

**Comment by Lukaydo** [comment]
Hi, in my laravel-inertia app I have some basic layout, which has a slot where goes a content. I am doing transition between pages like this:

` <transition :css="false" appear @before-appear="onBeforeAppear" @appear="onAppear">
                <slot />
            </transition>`

but downside of this is that there is no leave transition
