### ISSUE TITLE
Upload files

### ISSUE THREAD

**Issue by orumad** [inertiajs/inertia-vue#48]
Is there a way to upload files to the server (i.e. Laravel) with Inertia?

I can't figure out how to do that using for example `$inertia.post(...)`. I had reviewed the Inertia source code and not found a way to set the `'multipart/form-data'` header.

May be I need to use Axios itself instead of Inertia for this task.

**Comment by thoresuenert** [comment]
@orumad did you try to pass a formdata object to `$inertia.post()` ?

```js
$inertia.post(new FormData('file' => new File()));
```

**Comment by orumad** [comment]
@thoresuenert, yes I tried this. But it doesn't works. 

Thanks anyway.

**Comment by wadday** [comment]
> @orumad did you try to pass a formdata object to `$inertia.post()` ?
> 
> ```js
> $inertia.post(new FormData('file' => new File()));
> ```

it works, here is my upload method. in this method, I have handled multiple image uploads.

```
const formData = new FormData()
      this.files.forEach(file => {
        formData.append('images[]', file, file.name)
      })
      this.$inertia.post('/upload/url', formData)
        .then(()=> {
          this.files = [];
        })
        .catch(error => {
          Logger.log(error);
        })
```

**Comment by orumad** [comment]
So... yes it works out of the box!

I don't know what I did wrong but ¯\_(ツ)_/¯
