### ISSUE TITLE
Browser back button clicked then data not updating ?

### ISSUE THREAD

**Issue by bombiGo** [inertiajs/inertia-vue#49]
I have 2 pages. First page is my data list. Second page is data updated then I clicked browser go back button. My first page data list not changing but First page link clicked then it works. Help me ?

**Comment by reinink** [comment]
Yes, this makes sense. Inertia, as much as possible, follows standard browser behaviour. Which means when you clicking back (or forward) in history, you'll see the page as it was, the cached history values. It won't be reloaded, like when you click a link.
