### ISSUE TITLE
Check a visit status?

### ISSUE THREAD

**Issue by rakk7** [inertiajs/inertia-vue#54]
I am trying to add a loading spinner inside a button while submitting a form using:
`$inertia.post(url, data)`

It would be nice if Inertia support something like: `$inertia.busy`, `$inertia.successful` to check a visit status.

How do you guys hande something like this?

**Comment by thoresuenert** [comment]
@rakk7 you can see it how @reinink solves a lot of stuff in https://github.com/inertia/pingcrm

https://github.com/inertiajs/pingcrm/blob/a49456b323ea6082cf1958b99a1e94d68d4f2e7f/resources/js/Pages/Contacts/Create.vue#L70-L75

**Comment by rakk7** [comment]
@thoresuenert 

Yeah, I have found a way to do this. I was thinking that maybe this should be part of inertia itself.
