### ISSUE TITLE
is there an option to catch the return response in laravel?

### ISSUE THREAD

**Issue by codeitlikemiley** [inertiajs/inertia-vue#60]
if i use $inertia.post().then()

there is no way i can access the returned response
the response is intercepted directly by 
inertia modal that loads the error message from back end .

I need a ways to access response, is there a way i can access it please advice

**Comment by enzonotario** [comment]
If you get a modal, that means that your backend is not responding with a JSON and status 200. Try to put an early return in your controller, and you will se this in the .then:
```
return response()->json(['test' => 'testing']);
```

**Comment by sebastiandedeyne** [comment]
See #59 :)
