### ISSUE TITLE
[hint] 'Workaround' for styles in vue components

### ISSUE THREAD

**Issue by Naoray** [inertiajs/inertia-vue#61]
**tl;dr;**
run `yarn watch`, change anything in code, works!

---

I somehow missed the note on the documentation that you cannot use `<style>` tags inside Vuejs with Laravel Mix v4:

> Limitation: When using Laravel Mix (v4) with dynamic imports you cannot write styles within Vue files. As a workaround, you need to drop Mix entirely or downgrade to v3 due to current Webpack limitations (source).

However, I only run into the error after triggering `yarn dev` manually - was using `yarn watch` before... turns out that after running `yarn watch` and changing a single line, everything gets compiled as it should be and it's working flawlessly!

I know it's just a workaround, but it might be useful for others who don't want to wait until the issue of styles in vue components is solved.

**Comment by connecteev** [comment]
@Naoray thanks for sharing this tip

**Comment by connecteev** [comment]
@Naoray have you seen this? https://github.com/inertiajs/inertia-vue/issues/62

**Comment by sebastiandedeyne** [comment]
Since this is not an Inertia issue I'm closing this.

Thanks for sharing though!
