### ISSUE TITLE
Accessing Laravel's .env variables inside Inertia.js Vue files

### ISSUE THREAD

**Issue by connecteev** [inertiajs/inertia-vue#63]
I am starting with the Inertia Laravel example https://github.com/drehimself/inertia-example

which is nothing but Laravel with Vue in one codebase, using Inertia.js:
https://github.com/inertiajs/inertia-laravel 
plus 
https://github.com/inertiajs/inertia-vue

Everything is fine except that I am trying to access Laravel's .env variables inside my .vue component files

.env file:
```env
APP_NAME=ABC
```

In app\Providers\AppServiceProvider.php:
```php
public function register()
{
    Inertia::share('appName', env('APP_NAME'));
}
```

In resources\js\Home.vue component:
```vue
<template>
  <div>
        <span class="tw-text-left">{{ appName }}</span>
  </div>
</template>

<script>
export default {
  props: [
    "appName",
 ]
}
</script>
```

In my vue console, appName shows up blank. It should show "ABC" but doesn't.

Btw I also tried to inject the page data:

```  
<template>
  <div>
    <header>
      Welcome, {{ page.props.auth.user.first_name }} {{ page.props.auth.user.last_name }}
    </header>
    <nav>
      <!-- ... -->
    </nav>
    <article>
      <!-- ... -->
    </article>
  </div>
</template>

<script>
export default {
  inject: ['page'],
  // ...
}
</script>
``` 
(as per the suggestion [here](https://reinink.ca/articles/introducing-inertia-js)) but it doesn't seem to work and results in a console error.

What's going on here, and how I can access all my env variables, ideally without passing everything through the controller, which doesn't seem very efficient?

**Comment by rodrigopedra** [comment]
I don know if it was typing mistake on the code sample, but you have an extra space in you `'APP_NAME '` between the quotes. Laravel won't find that key (with an extra space) and the `env` helper will return `null` which renders to blank in Vue.

One more thing, avoid using the `env` helper outside config files. in production all the config files would be cached (running `php artisan config:cache` or `php artisan optimize`) which improve performance a lot. Also, I don 't have the reference right now, but I remember reading that accessing the .env file in each request is not a good thing regarding security.

You can access the same value through the config value (`config('app.name')`).

**Comment by connecteev** [comment]
@rodrigopedra you have a very good eye. I did remove the trailing space and it didnt make a difference. Also good tip about using config() instead of env(), thanks.
Still not sure how to access the env variables from the vue files though..

**Comment by enzonotario** [comment]
Hi! I use this, and works fine: https://laravel-mix.com/extensions/env-file

**Comment by jkniest** [comment]
You can already use `.env` variables in javascript with laravel when you prefix them with mix_

`process.env.MIX_MY_ENVIRONMENT_VARIABLE`

This is a build-in feature of laravel mix. You can't access all because of security reasons (for example the DB_PASSWORD, etc.).

In your case you could do something like this in your .env

```
APP_NAME="My cool app"
MIX_APP_NAME="${INDEX_NAME}"
```

Then you could access it in js like this:

`process.env.MIX_APP_NAME` without any backend code

**Comment by enzonotario** [comment]
ahh yes!! I use that just to get those variables in my `webpack.mix.js`

**Comment by connecteev** [comment]
@jkniest @enzonotario thank you, this is helpful. So is passing the data through Laravel Mix the only option?

**Comment by enzonotario** [comment]
nono, sorry, @jkniest is right, you just have to prefix your variables with `MIX_`, and you will be able to use them in Vue. What I said is just for if you want to use those variables in your `webpack.mix.js`

**Comment by connecteev** [comment]
@enzonotario @jkniest makes sense.

Btw I know that in the early days, inertia would "allow you" to pass data through using the AppServiceProvider into the Vue files. I no longer see that in the Readme / docs, and am curious if @reinink has an alternative approach.

**Comment by enzonotario** [comment]
it is still there: https://github.com/inertiajs/inertia-laravel/#sharing-data

I recommend you to check this repo, and play arround it: https://github.com/inertiajs/pingcrm

**Comment by connecteev** [comment]
@enzonotario thanks for the tip! I dug into pingcrm and got it working. Here's how, for those interested:
In AppServiceProvider:
```
        Inertia::share(function () {
            return [
                'app' => [
                    'name' => config('app.name'),
                ],
            ];
        });
```

In your vue file:
```
<template>
<div>
App name: {{ $page.app.name }}
</div>
</template>
```

The 2nd part is what I was missing..I was trying to accept the app.name prop, and was missing $page. 
Hope this helps somebody!
