### ISSUE TITLE
Recommended way of handling multi form/component pages

### ISSUE THREAD

**Issue by faustbrian** [inertiajs/inertia-vue#68]
Hey, been dabbling around with the inertia the last days and wondered something about pages that are composed of multiple components. Let's take below example.

```vue
<template>
    <layout :title="user.name">
        <edit-contact :user="user" />
        <edit-profile :user="user" />
        <edit-photo :user="user" />
        <export-gdpr :user="user" />
        <delete-account :user="user" />
    </layout>
</template>

<script>...</script>
```

Would this be perfectly fine and not interfere at all with how inertia and its state works or are there any recommendations on how to structure your components to avoid certain issues? Meaning for example to keep a whole page in a single component rather then splitting its elements into child components with their own responsibilities.

**Comment by georgehanson** [comment]
There should be no problem with this. I often split out my views into multiple components. The Inertia props will just get passed to the Vue component and you can pass whatever you need to child components accordingly.

It's best to think of Inertia more as a "Server-side" thing rather than the client side. In essence, the client side is just the consumer of the Inertia response.

**Comment by reinink** [comment]
Yup, well said @georgehanson.

What you're doing here looks totally fine @faustbrian. I often will create sub components within my page components like this. Works great! 👍 

There isn't really much special about Inertia when it comes to your components. They are really just regular Vue components, that get their data via props.

The _only_ thing you'll want to be careful with is if you have multiple forms on the page and are taking advantage of the "remember" functionality, used to cache local state in across browser history state. You'll need to set a unique remember key for each component. See [here](https://github.com/inertiajs/inertia-vue#remembering-local-component-state).

Good luck! 💪

**Comment by faustbrian** [comment]
Thanks, great to hear nothing has to change! Will keep the unique key in mind.
