### ISSUE TITLE
Add data attribute to <inertia-link>

### ISSUE THREAD

**Issue by reinink** [inertiajs/inertia-vue#7]
It might be cool to add a data attribute to <inertia-link>. For example:

```vue
<inertia-link href="/endpoint" method="post" :data="{ foo: bar }">...</inertia-link>
```

I honestly can't think of a great use-case for this right now, but if we're going to support non-GET methods, it only seems appropriate to support sending data with the request.

**Comment by alexbowers** [comment]
It'd be cool if that worked for GET and POST url's.

I'm thinking pagination, it'd be cool if the :data property could create the correct GET params to send over without us having to format the URL ourselves.
