### ISSUE TITLE
Keep a component mounted

### ISSUE THREAD

**Issue by MaximeWillinger** [inertiajs/inertia-vue#70]
I recently implemented Inertia (Laravel + Vue) in an experimental project, and so far it works great! Good job 👏 

I have one issue though. I have a component in my layout file containing an HTML5 `<audio>` and I need to keep it alive between page changes. Right know, it's re-mounted during every page change, making the audio element reloaded every time.

What would be the recommended approach?

**Comment by Juhlinus** [comment]
Hello @MaximeWillinger !

This is not supported as of right now. What you _can_ do is put the audio tag in your blade, which will allow the audio to play without interruption.

```html
<!DOCTYPE html>
<html class="h-full bg-grey-lighter">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <link href="{{ mix('/css/app.css') }}" rel="stylesheet">
    <script src="{{ mix('/js/app.js') }}" defer></script>
    @routes
</head>
<body class="font-sans leading-none text-grey-darkest antialiased">
@inertia

<audio src="https://freesound.org/data/previews/88/88570_1437649-lq.mp3" autoplay />
</body>
</html>
```

**Comment by MaximeWillinger** [comment]
Hi @Juhlinus 👋 Thanks for your reply!

As I'm using a custom reactive component to deal with `<audio>`, it would not be the best option. It would also prevent me from using my current implementation with Vuex states and mutations.

I would be very interested to know how @reinink imagines this kind of implementation in future Inertia releases, and if I can help in any way.

If I am not mistaken, the `<Inertia> component remains persistent. Perhaps there would be a solution by using a named slot here?

**Comment by rodrigopedra** [comment]
Have you tried wrapping the Inertia component into another component? The Inertia component works similary to the `RouteView` component from vue router.

On this "wrapper" you would keep anything you want to be persistent between requests.

I have tried it and it worked.

- `MasterComponent.vue`

~~~vue
<template>
    <div>
        <slot />

        <audio src="sample.mp3" autoplay />
    </div>
</template>

<script>
export default {
    name: 'MasterComponent',
};
</script>
~~~

- `app.js`

~~~js
// ...
render(h) {
render(h) {
    return h(MasterComponent, [
        h(InertiaApp, {
            props: {
                initialPage: JSON.parse(app.dataset.page),
                resolveComponent: page => files(`./Pages/${page}.vue`).default,
            },
        }),
    ]);
},
// ...
~~~

Note I use the require.context notation as showed in the readme, but it should work with the `import` as well.

**Comment by sebastiandedeyne** [comment]
That's an awesome idea and opens up a lot of interesting possibilities! Going to look into documenting this soon 👍

**Comment by MaximeWillinger** [comment]
@rodrigopedra I haven't thought of changing the `render` method. That's a great idea. I have tested and it works perfectly!

Thanks 👍
