### ISSUE TITLE
Data not replacing previous data with the same name when using reload

### ISSUE THREAD

**Issue by Jam0r85** [inertiajs/inertia-vue#72]
Not sure if this is intended, but when using this.$inertia.reload and using the data property, instead of replacing itself it just repeats in the url.

eg when using this method to cycle through a laravel pagination collection.

`
this.$inertia.reload({ method: 'get', data: { page: this.pagination.current_page - 1 }, preserveScroll: true, preserveState: true })
`

it results in

`
statements?page=2&page=1&page=2&page=3&page=2&page=1
`

**Comment by georgehanson** [comment]
Hey @Jam0r85, in my opinion this doesn't sound like something that should be the case. Please can you close this issue and raise it on the main [inertia](https://github.com/inertiajs/inertia) repository please? The `this.$inertia.reload()` isn't client implementation specific.

Thanks!

**Comment by reinink** [comment]
Looks like someone already did: https://github.com/inertiajs/inertia/issues/65 👍 

Closing this one.
