### ISSUE TITLE
CSRF token mismatch

### ISSUE THREAD

**Issue by rutvij2292** [inertiajs/inertia-vue#76]
Problem: When I am trying to make a request using axios normally without using inertia-link helper, I'm getting 419 error i.e. CSRF token mismatch?

Is there anyway I can make axios request and receive response in JSON format? 

Code:

```
// Laravel Side
public function userList() {
    return response()->json(["list" => $data]);
}

// Routes
Route::get('/users/list', 'UserController@userList');

// Vue File

mounted() {
    // Getting 419 error here after making a request using axios not $inertia.visit
    axios.get('/users/list')
        .then( response => { // DO STUFF }) 

    // QUESTION
    // how to receive JSON response using $inertia.visit ?
   this.$inertia.visit('/users/list', {method: 'GET' }) ?????

}
```

Thank you!
Rutvij

**Comment by m1guelpf** [comment]
Make sure you're setting `$addHttpCookie` to true in the VerifyCsrfToken middleware and have the `session.http_only` config key set to false (at least that's what made it work for me). You might also have to set withCredentials to true on axios side like so:

```js
axios.defaults.withCredentials = true;
```

**Comment by rutvij2292** [comment]
@m1guelpf Yes, I already have `$addHttpCookie` flag set it to `true` that's why I'm having an error of token mismatch. I'm not aware of `axios.defaults.withCrendtials`, by enabling `withCredentials` will resolve the issue? 

I am trying to find a way to pass a CRSF_TOKEN value in the `.defaults.headers.common['X-CSRF-TOKEN']`

**Comment by reinink** [comment]
See here: https://github.com/inertiajs/pingcrm/issues/32#issuecomment-517950144
