### ISSUE TITLE
419 CSRF-Token

### ISSUE THREAD

**Issue by divdax** [inertiajs/inertia-vue#81]
How do you deal with token mismatch (419) when submitting a form after idling a while?
Currently inertia open the default error modal.

Or maybe it's possible to prevent the "idle csrf token timeout"?

**Comment by RSpeekenbrink** [comment]
Preventing the CSRF token timeout kinda goes defeats the purpose of a CSRF token. When someone has been idling at a form for too long the current session simply times out. You could extend the sessions lifetime in laravel by editing the `lifetime` value in `config/session.php`.

Another way could be to warn the user that their session is about to expire by running a timer in the background, then reloading the csrf token when the user responds. You could do something like:

```
            let csrfToken = document.head.querySelector('meta[name="csrf-token"]');

            setInterval(refreshToken, 3600000); // 1 hour 

            function refreshToken(){
                if (!confirm('refresh session?')) return;

                axios.get('refresh-csrf').then(data => {
                    csrfToken = data; // the new token
                    setInterval(refreshToken, 3600000); // 1 hour 
                });
            }
```

Then in laravel routes:

```
Route::get('refresh-csrf', function(){
    return csrf_token();
});
```

**Comment by RSpeekenbrink** [comment]
If you mean how to deal with the error in inertia in another way than showing a modal you could edit the global handler like this: https://reinink.ca/articles/introducing-inertia-js#handling-exceptions

**Comment by divdax** [comment]
Oh, thank you @RSpeekenbrink! I like it!
