### ISSUE TITLE
<inertia-link> doesn't send X-XSRF-TOKEN header

### ISSUE THREAD

**Issue by nikazooz** [inertiajs/inertia-vue#9]
Hi 👋 

I'm encountering a strange issue... If I visit a page using `inertia-link` component the `X-XSRF-TOKEN` header is not sent, but if I use `Inertia.visit()` it is sent. This just makes `inertia-link` unusable f.e. in Laravel application for logout using POST method. My workaround for this is to use `Inertia.visit()` directly.

Do you have some idea what might cause this?

Cheers and again - thanks for this great library!

**Comment by jsbeckr** [comment]
Hey,

i had the same issue while developing a sample application with https://github.com/jsbeckr/inertia-django. Django uses the `X-CSRFToken` header.

But you can set the XSRF-Token header name and the cookie name (from which cooke axios will take the token from) like this (Django example):
```javascript
import axios from 'axios';

axios.defaults.xsrfCookieName = 'csrftoken'
axios.defaults.xsrfHeaderName = 'X-CSRFToken'
```

**Comment by nikazooz** [comment]
@jsbeckr This didn't solve my problem since axios was already finding the token correctly, but thanks anyway. 🙂 

I was able to find the cause of the problem, though. 😄 For future reference, if anyone is using something like Ziggy to handle routes on the front-end, don't pass the route object as `href` attribute to `inertia-link` component, or to `Inertia.visit()`, for that matter. Even though it can resolve to a string, the correct way is to pass the actual string. In the example of Ziggy, get it by calling the `url` method on the route.

I don't know the actual reason, but my guess is that axios needs URL given as actual string to determine whether to send the token header or not. In case it is given object that can be converted to string, it won't send this header.

I'll close this issue.

**Comment by reinink** [comment]
Yup, this is an annoying issue. I use a Vue mixin to avoid this issue:

```js
Vue.mixin({
  methods: {
    route: (...args) => window.route(...args).url()
  }
})
```
