### ISSUE TITLE
Vue single file components styles become global and persistent between route navigations

### ISSUE THREAD

**Issue by SPascareli** [inertiajs/inertia-vue#91]
I'm sorry I'm not able to give any proper examples now, but I noticed that when I define a `style` in one of my Vue components, the style becomes global and persists even when I load another route via <inertia-link>.

I am using laravel mix and Vue with inertia, later when I'm home I will show some examples.

**Comment by SPascareli** [comment]
My bad, I forgot to add `scoped` to the vue style, so the right way should be:
`<style scoped>
...
</style>
`

Please close the issue.

**Comment by reinink** [comment]
Glad you got it figured out. 👍
