### ISSUE TITLE
Will jQuery datatable work?

### ISSUE THREAD

**Issue by twf-nikhila** [inertiajs/inertia-vue#92]
Hello,

This package looks really promising.

In most of our projects, we use jQuery Datatable https://datatables.net/ and there isn't a good replacement of it available in VueJS. So wanted to know if it will support using this datatable script.

Thank you.

**Comment by reinink** [comment]
Hey @twf-nikhila, thanks for your interest in Inertia.js.

Yes, it's often possible to use jQuery and Vue together. I'd recommend reaching out to those communities for help, since this is quite outside the scope of Inertia.js.

Good luck! 👍
