### ISSUE TITLE
Cannot read property 'call' of undefined in Production

### ISSUE THREAD

**Issue by lucaros97** [inertiajs/inertia-vue#94]
When trying to deploy a Laravel + Inertia app it shows me this error in console:
`Cannot read property 'call' of undefined`

This is what my webpack.mix.js looks like:
```
const mix = require('laravel-mix');
const path = require('path');

mix.js('resources/js/app.js', 'public/js')
   .sass('resources/sass/app.scss', 'public/css')
   .webpackConfig({
    output: { chunkFilename: 'js/[name].js?id=[chunkhash]' },
    resolve: {
      alias: {
        vue$: 'vue/dist/vue.runtime.esm.js',
        '@': path.resolve('resources/js'),
      },
    },
  });
```

And this is what my app.js looks like:
```
import { InertiaApp } from '@inertiajs/inertia-vue'
import PortalVue from 'portal-vue'
import Vue from 'vue'

Vue.use(PortalVue)

Vue.config.productionTip = false
Vue.mixin({ methods: { route: window.route } })
Vue.use(InertiaApp)
Vue.use(PortalVue)
let app = document.getElementById('app')

new Vue({
  render: h => h(InertiaApp, {
    props: {
      initialPage: JSON.parse(app.dataset.page),
      resolveComponent: name => import(`@/Pages/${name}`).then(module => module.default),
    },
  }),
}).$mount(app)
```

PS. Everything works locally

**Comment by reinink** [comment]
This sounds to me like an outdated chunks issue in production. Basically when you make changes, and then deploy those changes to production, the JS files (chunks) change. Unless you do a full page reload and force a cache break, this will happen.

Do you have [asset versioning](https://inertiajs.com/asset-versioning) enabled?

**Comment by lucaros97** [comment]
Didn't used asset versioning but resolved with [this issue closed](https://github.com/inertiajs/inertia-vue/issues/69)

**Comment by reinink** [comment]
Nice, glad you got it figured out. 👍

**Comment by paulotra** [comment]
@lucaros97 how did you solve it? need help here i'm facing the same issue but asset versioning isn't working.

**Comment by lucaros97** [comment]
@paulotra resolved this way https://github.com/inertiajs/inertia-vue/issues/69#issuecomment-521737883

**Comment by butaminas** [comment]
For me, it was the way I was importing the scss file in a vue component.
Instead of `@import "~bootstrap/scss/mixins";` I had to change to `@import "~bootstrap/scss/_mixins.scss";` and it started working.

**Comment by GhulamRasoolNunari** [comment]
asdada
