### ISSUE TITLE
Issue with $inertia.post using GET

### ISSUE THREAD

**Issue by jam3sn** [inertiajs/inertia-vue#95]
Hi there, I'm implementing Inertia on a fresh project, using both the docs and pingcrm for reference. I've setup a Login component using `this.$inertia.post` however the request method is using `GET` instead of `POST`.

Component:
```
methods: {
    submit() {
        this.sending = true;
        this.$inertia.post('/login', this.form);
    }
}
```

Routes:
```
Route::get('/login')->name('login')->uses('Auth\LoginController@showLoginForm');
Route::post('/login')->name('login.attempt')->uses('Auth\LoginController@login');
```

Screenshot of the request:
![Network screenshot](https://i.imgur.com/m2XRRM7.png)

app.js:
```
require("./bootstrap");

import Vue from "vue";
import { InertiaApp } from "@inertiajs/inertia-vue";

Vue.use(InertiaApp);

const app = document.getElementById("app");

new Vue({
    render: h =>
        h(InertiaApp, {
            props: {
                initialPage: JSON.parse(app.dataset.page),
                resolveComponent: name =>
                    import(`@/Pages/${name}`).then(module => module.default)
            }
        })
}).$mount(app);
```

I'm having the same issue on my Register component, i've changed the endpoint to `/register/new`, so there's no other request types sharing the endpoint, just a post route, however inertia just uses `/register`. I've done fresh yarn builds, i've updated yarn and composer and done a cache refresh in my browser.

I'm not sure if i'm going wrong somewhere or theres a bug with the `$inertia` methods. If there's any other information I can provide, let me know. Hopefully I'm just missing something?

Thanks!

**Comment by reinink** [comment]
I suspect what's happening is it's doing a redirect server side after the POST request due to a form validation error, which is why Chrome is reporting it as a GET request.

**Comment by jam3sn** [comment]
Hi Jonathan, a form error would be correct, I was purposefully submitting incorrect and empty details to see how inertia handled this is the `$page.errors`, however it's using the default Laravel Auth controllers which should return the validation error instead of the index page of that controller. I don't believe chrome would change the request url from that?

**Comment by reinink** [comment]
> I was purposefully submitting incorrect and empty details to see how inertia handled this is the $page.errors, however it's using the default Laravel Auth controllers which should return the validation error instead of the index page of that controller.

Not with Inertia, since Inertia requests are not treated as "wants JSON" requests in Laravel, meaning instead of returning JSON, Laravel will do a redirect back to the page that submitted the request. I recommend reading more about this in the documentation [here](https://inertiajs.com/forms#server-side-validation). Hopefully that will clear it up for you. 👍 

> I don't believe chrome would change the request url from that?

Yes, if an XHR request does a server-side redirect, Chrome will update the request in devtools to reflect that. This can make debugging things a little more difficult.
