### ISSUE TITLE
Why use Inertia instead of Vue's Single Page Application routing

### ISSUE THREAD

**Issue by mohammedjammeh** [inertiajs/inertia-vue#99]
This is more of a question rather than an issue. I am quite new to Vue so please bear with me.

I am currently working on a Laravel / Vue project whereby I am planning to implement SPA routing. As I was watching tutorials, I learnt that Vue allows one to add client-side routing. However, I later came across Inertia and I am now not sure whether to just stick to Vue's routing or use this package. On the Inertia web page, Jonathan mentioned that: 

> Inertia allows you to create fully client-side rendered, single-page apps, without much of the complexity that comes with modern SPAs.

So I am wondering what are some of these complexities that come with SPAs which Inertia actually solves?

The reason why I am planning to build my project as a SPA is because I will be playing sound using the Spotify API so it will be nice if a user can access different parts of the application without interfering with the Sound Player which will be implemented using Vue. In this case, would it better to Inertia instead of Vue's normal client-side routing?

**Comment by nmsmith22389** [comment]
Inertia doesn't really come into play when using external third-party APIs. I'd recommend checking out the documentation to get a better idea of what it actually does.
